baseURL = "https://www.foodogsquared.one"
title = "foodogsquared"
languageCode = "en"
enableGitInfo = true
copyright = "© Gabriel Arazas"
summaryLength = 0
timeZone = "UTC"

[params]
mainSections = ["posts", "projects"]
toc = true
extraNotes = """
This site uses [medium-zoom](https://github.com/francoischalifour/medium-zoom) and lots of modern CSS features for the life of me.
For analytics, it uses [GoatCounter](https://goatcounter.com/).
"""

[pagination]
pagerSize = 40

[taxonomies]
tag = "tags"
series = "series"

[[module.imports]]
path = "github.com/foo-dogsquared/hugo-theme-more-contentful"

[[module.imports]]
path = "github.com/foo-dogsquared/hugo-mod-web-feeds"

[mediaTypes."application/atom+xml"]
suffixes = ["atom"]

[mediaTypes."application/rss+xml"]
suffixes = ["rss"]

[outputFormats.RSS]
mediaType = "application/rss+xml"
baseName = "index"
isPlainText = false

[outputFormats.Atom]
mediaType = "application/atom+xml"
baseName = "index"
isPlainText = false

[outputs]
home = ["HTML", "ATOM", "RSS", "JSON"]
section = ["HTML", "ATOM", "RSS", "JSON"]

[security.exec]
allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^asciidoctor$', '^git$']

[security.funcs]
getenv = [ "^LAST_COMMIT_DATE$" ]
