[asciidocExt]
extensions = [
  "asciidoctor-bibtex",
  "asciidoctor-diagram",
  "asciidoctor-foodogsquared-extensions",
]
trace = true
workingFolderCurrent = true

[asciidocExt.attributes]
toc = true
sectanchors = true
"figure-caption!" = true
source-highlighter = "rouge"
allow-uri-read = true
experimental = true
linkcss = true
cache-uri = true
reproducible = true
stem = "latexmath"

avatarsdir = "/icons/avatars"
avatarstype = "avif"

icons = "image"
iconsdir = "/icons/asciidoctor"
icontype = "svg"

# asciidoctor-bibtex
bibtex-file = "./assets/bibliography.bib"
bibtex-order = "alphabetical"
bibtex-throw = true

# asciidoctor-tabs
tabs-sync-option = true
