dist: xenial

# installing Hugo from the snap store'
# https://snapcraft.io/hugo
addons:
  snaps:
    - hugo
    - name: ruby
      confinement: classic 
script:
  - gem --version
  - gem install asciidoctor
  - asciidoctor --version
  - hugo
deploy:
  local_dir: "public/"
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  on:
    branch: master
    