dist: bionic

# installing Hugo from the snap store'
#   https://snapcraft.io/hugo
before_install:
  - sudo apt-get update
  - sudo apt-get ruby
  - sudo apt-get install hugo
script:
  - asciidoctor --version
  - hugo
deploy:
  local_dir: "public/"
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  on:
    branch: master
    