dist: bionic

# installing Hugo from the snap store'
#   https://snapcraft.io/hugo
before_install:
  - sudo apt-get update
  - sudo apt-get install ruby
  - wget https://github.com/gohugoio/hugo/releases/download/v0.57.0/hugo_0.57.0_Linux-64bit.deb
  - sudo dpkg -i hugo_0.57.0_Linux-64bit.deb
script:
  - asciidoctor --version
  - hugo
deploy:
  local_dir: "public/"
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  on:
    branch: master
    