baseURL = "https://foo-dogsquared.github.io/blog"
languageCode = "en-us"
title = "A Hack's Code"
description = "A blog of a hack."
summaryLength = 0
paginate = 5
disqusShortname = "foodogsquared"
copyright = "Unless explicitly stated, all content released here are licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0)."
googleAnalytics = "UA-126718538-1"
theme = "terminal-plus-minus"
canonifyURLs = true

[author]
    name = "Gabriel Arazas"
    alias = "foo-dogsquared"
    email = "foo.dogsquared@gmail.com"

[menu]
    [[menu.main]]
        identifier = "articles"
        name = "Posts"
        url = "posts/"

    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "about/"

    [[menu.main]]
        identifier = "archives"
        name = "Archives"
        url = "archives/"

    [[menu.main]]
        identifier = "rss"
        name = "RSS"
        url = "index.xml/"

[params]
    subtitle = "Computer Engineering Student"
    keywords = ["Gabriel Arazas", "foo-dogsquared", "blog", "computer", "mathematics"]
    
    showPostsOnHome = true
    showPageTypeIcon = true

    enableSyntaxHighlighting = true
    syntaxHighlighter = "prismjs"
    enableBreadcrumbs = true
    contentIsStyled = true