baseURL = "https://foo-dogsquared.github.io/"
languageCode = "en-us"
title = "Gabriel Arazas"
enableGitInfo = true
summaryLength = 0
paginate = 40
copyright = """
Unless explicitly stated, all content released here are licensed under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/).
"""
canonifyURLs = true


[module]
  [[module.imports]]
    path = "github.com/foo-dogsquared/hugo-theme-more-contentful"

  [[module.imports]]
    path = "github.com/foo-dogsquared/hugo-web-feeds"


[markup]
  [markup.asciidocExt]
    extensions = ["asciidoctor-diagram"]
    [markup.asciidocExt.attributes]
    toc = true
    sectanchors = true


[author]
    [foo-dogsquared]
        name = "Gabriel Arazas"
        alias = "foo-dogsquared"
        email = "foo.dogsquared@gmail.com"

[mediaTypes]
    [mediaTypes."application/atom+xml"]
        suffixes = ["atom"]
    
    [mediaTypes."application/rss+xml"]
        suffixes = ["rss"]

[outputFormats]
    [outputFormats.RSS]
        mediaType = "application/rss+xml"
        baseName = "index"
        isPlainText = false
    
    [outputFormats.Atom]
        mediaType = "application/atom+xml"
        baseName = "index"
        isPlainText = false

[outputs]
    home = ["HTML", "ATOM", "RSS", "JSON"]
    section = ["HTML", "ATOM", "RSS", "JSON"]

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About me"
        url = "about/"

    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "blog/"

    [[menu.main]]
        identifier = "archives"
        name = "Archives"
        url = "archives/"

    [[menu.links]]
        identifer = "blog"
        name = "Blog"
        url = "/blog/"

    [[menu.links]]
        identifier = "Code"
        name = "Code"
        url = "https://github.com/foo-dogsquared/"

    [[menu.links]]
        identifer = "notes"
        name = "Notes"
        url = "https://github.com/foo-dogsquared/wiki"

    [[menu.links]]
        identifer = "music"
        name = "Music"
        url = "https://www.youtube.com/channel/UCuMiU9bzATu5oTp-vhOlL2Q"


[permalinks]
    posts = "/blog/posts/:title/"

[params]
    mainSections = ["posts", "projects"]
    toc = true
    extraNotes = """
    This site uses [Prism](https://prismjs.com/), [MathJax](https://www.mathjax.org/), and [medium-zoom](https://github.com/francoischalifour/medium-zoom).
    For analytics, it uses [GoatCounter](https://goatcounter.com/).
    """
