baseURL = "https://www.foodogsquared.one"
languageCode = "en-us"
title = "Gabriel Arazas"
enableGitInfo = true
paginate = 40
copyright = "© foodogsquared"
canonifyURLs = true
summaryLength = 0
timeZone = "UTC"

[[module.imports]]
path = "github.com/foo-dogsquared/hugo-theme-more-contentful"

[[module.imports]]
path = "github.com/foo-dogsquared/hugo-mod-web-feeds"

[markup.asciidocExt]
extensions = [
  "asciidoctor-foodogsquared-extensions",
  "asciidoctor-tabs",
  "asciidoctor-bibtex",
]
trace = true
workingFolderCurrent = true

[markup.asciidocExt.attributes]
toc = true
sectanchors = true
"figure-caption!" = true
source-highlighter = "rouge"
allow-uri-read = true
experimental = true
linkcss = true

# asciidoctor-bibtex
bibtex-file = "./assets/bibliography.bib"
bibtex-order = "alphabetical"
bibtex-throw = true

# asciidoctor-tabs
tabs-sync-option = true

[author.foo-dogsquared]
name = "Gabriel Arazas"
alias = "foo-dogsquared"
email = "foodogsquared@foodogsquared.one"

[mediaTypes."application/atom+xml"]
suffixes = ["atom"]

[mediaTypes."application/rss+xml"]
suffixes = ["rss"]

[outputFormats.RSS]
mediaType = "application/rss+xml"
baseName = "index"
isPlainText = false

[outputFormats.Atom]
mediaType = "application/atom+xml"
baseName = "index"
isPlainText = false

[outputs]
home = ["HTML", "ATOM", "RSS", "JSON"]
section = ["HTML", "ATOM", "RSS", "JSON"]

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "about/"

    [[menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "contact/"

    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "posts/"

    [[menu.links]]
        identifer = "posts"
        name = "Posts"
        url = "/posts/"

    [[menu.links]]
        identifier = "code"
        name = "Code"
        url = "https://code.foodogsquared.one/"

    [[menu.links]]
        identifer = "wiki"
        name = "Wiki"
        url = "https://wiki.foodogsquared.one/"

    [[menu.links]]
        identifer = "music"
        name = "Music"
        url = "https://www.youtube.com/channel/UCuMiU9bzATu5oTp-vhOlL2Q"

[params]
mainSections = ["posts", "projects"]
toc = true
extraNotes = """
This site uses [medium-zoom](https://github.com/francoischalifour/medium-zoom) and lots of modern CSS features for the life of me.
For analytics, it uses [GoatCounter](https://goatcounter.com/).
"""

[security.exec]
allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']

[security.funcs]
getenv = [ "^LAST_COMMIT_DATE$" ]
