baseURL = "https://foo-dogsquared.github.io/blog/"
languageCode = "en-us"
title = "A Hack's Code"
summaryLength = 0
paginate = 40
copyright = "Unless explicitly stated, all content released here are licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0)."
canonifyURLs = true


[module]
  [[module.imports]]
    path = "github.com/foo-dogsquared/hugo-theme-more-contentful"

  [[module.imports]]
    path = "github.com/foo-dogsquared/hugo-web-feeds"


[markup]
  [markup.asciidocExt]
    extensions = ["asciidoctor-diagram"]
    [markup.asciidocExt.attributes]
    toc = true
    sectanchors = true


[author]
    [foo-dogsquared]
        name = "Gabriel Arazas"
        alias = "foo-dogsquared"
        email = "foo.dogsquared@gmail.com"

[mediaTypes]
    [mediaTypes."application/atom+xml"]
        suffixes = ["atom"]
    
    [mediaTypes."application/rss+xml"]
        suffixes = ["rss"]

[outputFormats]
    [outputFormats.RSS]
        mediaType = "application/rss+xml"
        baseName = "index"
        isPlainText = false
    
    [outputFormats.Atom]
        mediaType = "application/atom+xml"
        baseName = "index"
        isPlainText = false

[outputs]
    home = ["HTML", "ATOM", "RSS", "JSON"]
    section = ["HTML", "ATOM", "RSS", "JSON"]

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "about/"

    [[menu.main]]
        identifier = "archives"
        name = "Archives"
        url = "archives/"

[params]
    mainSections = ["posts", "projects"]
    toc = true
