baseurl = "https://foo-dogsquared.github.io/blog/"
languageCode = "en-us"
theme = "terminal"
paginate = 5
summaryLength = 15
disqusShortname = "foodogsquared"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeNames = [ "posts", "projects" ]
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  favicon = "logo.jpg"

  [params.blog]
    [params.blog.author]
      name = "Gabriel Arazas"
      alias = "foo-dogsquared"
    [params.blog.contact]
      [params.blog.contact.github]
        name = "GitHub"
        link = "https://github.com/foo-dogsquared"
      
      [params.blog.contact.gitlab]
        name = "GitLab"
        link = "https://github.com/foo-dogsquared"
      
      [params.blog.contact.twitter]
        name = "Twitter"
        link = "https://twitter.com/foo_dogsquared"
      
      [params.blog.contact.keybase]
        name = "Keybase"
        link = "https://keybase.io/foo_dogsquared"

[languages]
  [languages.en]
    title = "A Hack's Code"
    subtitle = "A blog of a hack."
    keywords = "hack, code, foo-dogsquared, Gabriel Arazas"
    copyright = "2019 © Gabriel Arazas"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read my other posts"

    [languages.en.params.logo]
      logoText = "A Hack's Code"
      logoHomeLink = "/blog/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "home"
        name = "Home"
        url = "https://foo-dogsquared.github.io"

      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"

      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
