baseURL = "https://foo-dogsquared.github.io/blog/"
languageCode = "en-us"
title = "A Hack's Code"
summaryLength = 0
paginate = 40
copyright = "Unless explicitly stated, all content released here are licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0)."
googleAnalytics = "UA-126718538-1"
theme = "arch-terminal"
canonifyURLs = true

[author]
    name = "Gabriel Arazas"
    alias = "foo-dogsquared"
    email = "foo.dogsquared@gmail.com"

[mediaTypes]
    [mediaTypes."application/atom+xml"]
        suffixes = ["atom"]
    
    [mediaTypes."application/rss+xml"]
        suffixes = ["rss"]

[outputFormats]
    [outputFormats.RSS]
        mediaType = "application/rss+xml"
        baseName = "index"
        isPlainText = false
    
    [outputFormats.Atom]
        mediaType = "application/atom+xml"
        baseName = "index"
        isPlainText = false

[outputs]
    home = ["HTML", "ATOM", "RSS", "JSON"]
    section = ["HTML", "ATOM", "RSS", "JSON"]

[menu]
    [[menu.main]]
        identifier = "articles"
        name = "Posts"
        url = "posts/"

    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "about/"

    [[menu.main]]
        identifier = "archives"
        name = "Archives"
        url = "archives/"

    [[menu.main]]
        identifier = "feeds"
        name = "Feeds"
        url = "feeds/"


[params]
    subtitle = "Computer Engineering Student"
    keywords = ["Gabriel Arazas", "foo-dogsquared", "blog", "computer", "mathematics"]
    
    enableThemeToggle = true
    enableMathjax = true
    enableBreadcrumbs = true
    # enableContentImageZoom = true
    mainSections = ["posts", "projects"]

[privacy]
    [privacy.googleAnalytics]
        anonymizeIP = true
        respectDoNotTrack = true
        useSessionStorage = true