[build]
publish = "public/"
command = "make build -e"

[context.production.environment]
HUGO_BASEURL = "$DEPLOY_URL"

[context.branch-deploy]
command = "make build-draft -e"
environment.HUGO_BASEURL = "$DEPLOY_PRIME_URL"

[context.deploy-preview]
command = "make build-draft -e"
environment.HUGO_BASEURL = "$DEPLOY_PRIME_URL"
