[build]
publish = "public/"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.107.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
HUGO_BASE_URL = "$DEPLOY_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.107.0"
HUGO_BASE_URL = "$DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.107.0"

[context.deploy-preview]
command = "hugo --buildDrafts --buildFuture --buildExpired --baseURL $DEPLOY_PRIME_URL"
