[build]
publish = "public/"
command = "gem install bundler -v '~> 2.3' && bundle && hugo --gc --minify"

[context.production]
command = "gem install bundler -v '~> 2.3' && bundle && hugo --gc --minify --baseURL $URL"

[context.production.environment]
RUBY_VERSION = "3.0.4"
HUGO_VERSION = "0.107.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.branch-deploy]
command = "gem install bundler -v '~> 2.3' && bundle && hugo --buildDrafts --buildFuture --buildExpired --baseURL $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
RUBY_VERSION = "3.0.4"
HUGO_VERSION = "0.107.0"
HUGO_ENV = "development"

[context.deploy-preview]
command = "gem install bundler -v '~> 2.3' && bundle && hugo --buildDrafts --buildFuture --buildExpired --baseURL $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
RUBY_VERSION = "3.0.4"
HUGO_ENV = "development"
HUGO_VERSION = "0.107.0"

