[build]
publish = "public/"
command = "rake build"

[context.branch-deploy]
command = "rake build[branch-deploy,$DEPLOY_PRIME_URL]"

[context.deploy-preview]
command = "rake build[deploy-preview,$DEPLOY_PRIME_URL]"
